FROM jenkins/jenkins:lts-jdk17

USER root

# Install Docker CLI
RUN apt-get update && \
    apt-get install -y docker.io && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Create docker group.
# The GID will be adjusted when the container starts.
RUN groupadd -f docker && \
    usermod -aG docker jenkins

USER jenkins