version: "3.8"

services:
  jenkins:
    build: .
    container_name: jenkins
    privileged: true

    ports:
      - "8080:8080"
      - "50000:50000"

    volumes:
      - jenkins_home:/var/jenkins_home

      # Docker Desktop Docker socket
      - /run/host-services/docker.proxy.sock:/var/run/docker.sock

      # Existing .env
      - /run/desktop/mnt/host/c/Users/mrami/SpringBootProject/eKart/.env:/var/jenkins_env/.env:ro

      # Kubernetes config
      - C:/Users/mrami/.kube:/var/jenkins_home/.kube:ro

    restart: unless-stopped

volumes:
  jenkins_home:
    external: true
    name: jenkins-docker_jenkins_home