FROM jenkins/jenkins:lts-jdk17

USER root

RUN apt-get update &&\
apt-get install -y docker.io curl ca-certificates &&\
apt-get clean &&\
rm -rf /var/lib/apt/lists/*

RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" &&
install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl &&
rm kubectl

USER root
