services:

  mongodb:
    image: mongo:6.0
    container_name: ekartmongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: my_database

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ekart-app
    ports:
      - "8081:8081"
    env_file:
      - /var/jenkins_env/.env
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/my_database
      ENVIRONMENT: container
    depends_on:
      - mongodb

  frontend:
    build:
      context: ../frontend/ECommerce
      dockerfile: Dockerfile
    container_name: docker-react-app
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mongo-data: