services:

  mongodb:
    image: mongo:latest
    container_name: ekartmongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: my_database

  backend:
    build:
      context: C:/Users/mrami/SpringBootProject/eKart
      dockerfile: Dockerfile
    container_name: ekart-app
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/my_database
      ENVIRONMENT: container
    depends_on:
      - mongodb

  frontend:
    image: nginx:alpine
    container_name: docker-react-app
    ports:
      - "5173:80"
    volumes:
      - C:/Users/mrami/practice2/ECommerce/dist:/usr/share/nginx/html:ro
    depends_on:
      - backend

volumes:
  mongo-data: